[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "bun run build"
  publish = "public"

[[redirects]]
  from = "/api/v1/login/empresa"
  to = "http://zaal.no-ip.info:8083/api/v1/login/empresa"
  status = 200

[[headers]]
  for = "/api/*"
  headers = ["Access-Control-Allow-Origin: *"]
