[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[redirects]
  # Redireciona todas as solicitações para o backend Ngrok
  /* = "https://1290-200-164-236-60.ngrok-free.app/api/v1/"



[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"