[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://zaalcashback.netlify.app/api/v1/login/empresa"
  to = "http://zaal.no-ip.info:8083/api/v1/login/empresa"
  status = 200
  method = "POST"