PUT http://zaal.no-ip.info:8083/api/v1/anuncios/4
Content-Type: image/jpeg
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy56YWFsLmNvbS5ici8iLCJmdWxsX25hbWUiOiJaQUFMIiwidXBuIjoiMTAxIiwiZ3JvdXBzIjpbIklOVEVHUkFET1IiXSwiaWF0IjoxNzE2NTYxMzY0LCJleHAiOjI2NjI2NDEzNjQsImp0aSI6Ijk2NTFjZTJmLTc0ZTAtNDM1Ni1iMWViLWQwZWU5ZDhiMmQ1MSJ9.ZmLmEBb5Xn4WjdKoMzvbqLg9aRBn1Ps2mTxW9dXYShCAggltT5oxURv3SvTLgpHpfSph77BAI8Ox5uBvW0ZhhZjBx71ZQbs0Wh0um542O9b5RQzDSOirW3_iNAQYOhZwJI39SXeS166AOdnFW7qSqC0vQHp9ToExXkYzuvPzCdAEZD2Br1eyZK6bXd12wMF-Mrl3yYePwBpZ2nPpy6Y8ntGkYPi0l06OqiJ5jAOJSclezPhRjd0c_pa2mm_kvpPELS4J2Y2TNf4P7QCHhVDMBTTLhF7SoEohGQA8qUl1SZwxPJC-2Z7XgHk9eCbnOxKV-RjNU1UtePMvh0gxVRWqTg

{
    "conteudo": "Camisa Nike | A melhor camisa criada pela Nike.",
    "cupom": "NIKE20",
    "descricao": "Camisa Nike",
    "inicio": "2024-06-06T03:00:00.000Z",
    "tipoDesconto": "PORCENTAGEM",
    "validade": "2025-07-09T03:00:00.000Z",
    "valorDesconto": 20,
    "valorMaximo": 100,
    "valorMinimo": 100,
    "cnpj": "15379227000167",
    "inscricaoEstadual": "05709795"
}